### ISSUE TITLE
How to circulate data from parent component to child component？

### ISSUE THREAD

**Issue by sunlianlong** [zuixjs/zuix#10]
Currently studying zuix and looking at the zuix-web-flix project, I find that the generation of the Top rated on Web Flix list in the project is somewhat incomprehensible. The service is requested in the controllers/movie_db structure, but only one data is applied at a time? I think it's better for the parent component to get data and pass it on to the child component, but there are no relevant examples. In addition, there are many APIs that are not mentioned in the document. Many APIs don't know what the specific role is.
![image](https://user-images.githubusercontent.com/22101668/63739706-cbcd0d80-c8c0-11e9-85f7-e6f4d7e0de80.png)

**Comment by genemars** [comment]
This is because in this example all movie lists are [static](https://github.com/zuixjs/zuix-web-flix/blob/master/source/pages/home/list_top_rated.html), there is no controller providing the movie list, but there is a controller attached to each item (controllers/movie_db) that will make a request for fetching item data and that is only fetched when the item itself comes visible in the viewport (lazy-loading).
A new version of `zuix` is coming soon with all updated documentation. This will include currently undocumented features and more examples.
In the meantime feel free to ask for support here even if you need clarifications about implementing something that is not covered in the examples or docs.

**Comment by orbrbs** [comment]
@genemars did this new version occur?
