### ISSUE TITLE
Any overview explanation for source structure / architecture

### ISSUE THREAD

**Issue by yemkhaung** [zuixjs/zuix#7]
Love the idea of loading components from external servers and lazy loading stuff.
It is a simple and awesome library.
I've been fed up with overly abstracted JS frameworks and would like to try out this one.

Although I had a few years experience with Backend, I am beginner at Frontend and Javascript  stuff.  
Would love to dig into sources and understand implementation details more and it would help a lot if there were any overview explanation about library architecture, source structures, etc.

**Comment by genemars** [comment]
A good starting point is the `CONTRIBUTING.md` file.
II'll write down some additional backgrounds. 
This project does not use any transpiler option, so the source code is written in a *compatible* way, so that just merging the files will create a valid file of the library.
This process is anyway automated with 'gulp` scripts that make use of:
- **browserify**
that generates `zuix.js` and `zuix-bundler.js`. The starting point for the first one is `./src/main.js`, while for the latter is `./src/bundler.js`.
- **google-closure**
to make code verification against `ECMASCRIPT6_STRICT` and to generate minified versions of the libraries with relative `.map` files.
- **dox**
to generate the JSON files out of JSDoc comments used in the source code. These files are used to display the API documentation in the website. It also generate the *TypeScript* definition file. 
The scrips are located in the `./build` folder.
The source code is structured in classes obtained with closures, the use of `prototype` and JSDoc comments, in a way that migrating to the use of the `class` facility will be straightforward.

If there's more you want to know just ask.

**Comment by yemkhaung** [comment]
Honestly, I think I  need to google the terms you just used to make sense of them and connect the dots.
Sorry, beginner here. 😅

I'll start at contributor documentation and I'll put more questions later. 

Thanks for the explanation.

**Comment by genemars** [comment]
That's ok. You can start as a end-user, and use the library for your projects. Especially because you're a beginner you can help more in finding out the best way to improve the documentation and the library itself.
